    query BoardWithListsAndCards($id: ID!) {
        board(id: $id) {
            id
            title
            color
            owner {
                id
            }
            lists {
                id
                title
                board_id
                board {
                    owner {
                        id
                    }
                }
                cards {
                    id
                    title
                    order
                    owner {
                        id
                    }
                    list {
                        id
                    }
                }
            }
        }
    }
